name: LTS CI

on:
  push:
    branches: 
      - 'lts'
  pull_request:
    branches: 
      - 'lts'

jobs:
  docker:
    environment: dockerhub_staging
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set Docker Image Tag
        run: |
          GITHUB_BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          [[ ${GITHUB_BRANCH_NAME} == "master" ]] && GITHUB_BRANCH_NAME=latest
          echo "IMAGE_TAG=$(echo ${GITHUB_BRANCH_NAME})" >> $GITHUB_ENV
      -
        name: Build and Push Image to DockerHub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "joglomedia/jenkins-docker:${{ env.IMAGE_TAG }}"